
export default JSON.parse(`[
    {
        "ok": false,
        "processo": "10421720054201825",
        "res": null
    },
    {
        "ok": true,
        "processo": "10469724341201868",
        "res": [
            {
                "inscricao": "40 8 19 000024-58",
                "processoAdministrativo": "10469 724341/2018-68",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "8900",
                "nomeReceita": "DIV.ATIVA-ITR EX 97 E POSTERIO",
                "codigoSerie": "8",
                "nomeSerie": "IMPOSTO TERRITORIAL RURAL",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "445.597,72",
                "valorTotalInscritoIndex": "418.755,48",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "662.832,96",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "445.597,72",
                "valorRemanescenteIndex": "418.755,48",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "3267317",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4081900002458"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "10480723450201818",
        "res": [
            {
                "inscricao": "40 1 19 001772-81",
                "processoAdministrativo": "10480 723450/2018-18",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "18.352,01",
                "valorTotalInscritoIndex": "17.246,50",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "25.669,75",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "18.352,01",
                "valorRemanescenteIndex": "17.246,50",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4011900177281"
            }
        ],
        "total": 1
    },
    {
        "ok": false,
        "processo": "10480726818201891",
        "res": null
    },
    {
        "ok": true,
        "processo": "10480729933201656",
        "res": [
            {
                "inscricao": "40 3 19 000160-70",
                "processoAdministrativo": "10480 729933/2016-56",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3578",
                "nomeReceita": "DIV.ATIVA-IPI",
                "codigoSerie": "3",
                "nomeSerie": "IMPOSTO SOBRE PRODUTOS INDUSTRIALIZADOS",
                "codigoOrgaoJustica": "403377",
                "nomeOrgaoJustica": "SECAO JUDICIARIA DE PE EM GOIANA",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "4.012.155,74",
                "valorTotalInscritoIndex": "3.770.468,63",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "6.467.992,58",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "4.012.155,74",
                "valorRemanescenteIndex": "3.770.468,63",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4031900016070"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "10480733443201221",
        "res": [
            {
                "inscricao": "40 1 19 001775-24",
                "processoAdministrativo": "10480 733443/2012-21",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "2.602,67",
                "valorTotalInscritoIndex": "2.445,88",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "5.260,05",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "2.602,67",
                "valorRemanescenteIndex": "2.445,88",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4011900177524"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "10480903863201361",
        "res": [
            {
                "inscricao": "40 6 19 013501-29",
                "processoAdministrativo": "10480 903863/2013-61",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "1804",
                "nomeReceita": "DIV.ATIVA-CONTRIBUICAO SOCIAL",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "40.006,56",
                "valorTotalInscritoIndex": "37.596,60",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "76.413,66",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "40.006,56",
                "valorRemanescenteIndex": "37.596,60",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "DCOMP",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901350129"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "10480903864201314",
        "res": [
            {
                "inscricao": "40 6 19 013502-00",
                "processoAdministrativo": "10480 903864/2013-14",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "1804",
                "nomeReceita": "DIV.ATIVA-CONTRIBUICAO SOCIAL",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "27.620,39",
                "valorTotalInscritoIndex": "25.956,56",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "52.232,26",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "27.620,39",
                "valorRemanescenteIndex": "25.956,56",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "DCOMP",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901350200"
            },
            {
                "inscricao": "40 2 19 006683-20",
                "processoAdministrativo": "10480 903864/2013-14",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3551",
                "nomeReceita": "DIV.ATIVA-IRPJ",
                "codigoSerie": "2",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA JURIDICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "80.054,82",
                "valorTotalInscritoIndex": "75.232,41",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "152.799,29",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "80.054,82",
                "valorRemanescenteIndex": "75.232,41",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "DCOMP",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4021900668320"
            }
        ],
        "total": 2
    },
    {
        "ok": true,
        "processo": "11971720092201571",
        "res": [
            {
                "inscricao": "40 6 19 013986-79",
                "processoAdministrativo": "11971 720092/2015-71",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "4834",
                "nomeReceita": "R D ATIVA - MULTA ISOLADA",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "403385",
                "nomeOrgaoJustica": "SECAO JUDICIARIA DE PE EM JABOATAO DOS GUARARAPES",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "65.873,27",
                "valorTotalInscritoIndex": "61.905,12",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "104.183,81",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "65.873,27",
                "valorRemanescenteIndex": "61.905,12",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901398679"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "11971720154201898",
        "res": [
            {
                "inscricao": "40 7 19 004392-20",
                "processoAdministrativo": "11971 720154/2018-98",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "19/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "0810",
                "nomeReceita": "DIV.ATIVA-PIS",
                "codigoSerie": "7",
                "nomeSerie": "PROG INT SOCIAL/PROG FORM PATR SERV PUBL",
                "codigoOrgaoJustica": "403385",
                "nomeOrgaoJustica": "SECAO JUDICIARIA DE PE EM JABOATAO DOS GUARARAPES",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "4.130,89",
                "valorTotalInscritoIndex": "3.882,04",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "4.953,31",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "4.130,89",
                "valorRemanescenteIndex": "3.882,04",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4071900439220"
            },
            {
                "inscricao": "40 6 19 013940-96",
                "processoAdministrativo": "11971 720154/2018-98",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "19/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "4493",
                "nomeReceita": "DIV.ATIVA-COFINS",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "403385",
                "nomeOrgaoJustica": "SECAO JUDICIARIA DE PE EM JABOATAO DOS GUARARAPES",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "33.761,01",
                "valorTotalInscritoIndex": "31.727,29",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "40.482,54",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "33.761,01",
                "valorRemanescenteIndex": "31.727,29",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901394096"
            }
        ],
        "total": 2
    },
    {
        "ok": true,
        "processo": "13405000369200281",
        "res": [
            {
                "inscricao": "40 4 19 018370-31",
                "processoAdministrativo": "13405 000369/2002-81",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "8822",
                "nomeReceita": "DIV.ATIVA-SIMPLES",
                "codigoSerie": "4",
                "nomeSerie": "TRIBUTOS DIVERSOS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "52.217,47",
                "valorTotalInscritoIndex": "49.071,78",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "162.155,04",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "52.217,47",
                "valorRemanescenteIndex": "49.071,78",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4041901837031"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "13433000076200267",
        "res": [
            {
                "inscricao": "40 2 19 006832-06",
                "processoAdministrativo": "13433 000076/2002-67",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "19/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3551",
                "nomeReceita": "DIV.ATIVA-IRPJ",
                "codigoSerie": "2",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA JURIDICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "44.725,14",
                "valorTotalInscritoIndex": "47.704,55",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "183.038,66",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "44.725,14",
                "valorRemanescenteIndex": "47.704,55",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4021900683206"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "14770720119201742",
        "res": [
            {
                "inscricao": "40 6 19 014000-88",
                "processoAdministrativo": "14770 720119/2017-42",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "4834",
                "nomeReceita": "R D ATIVA - MULTA ISOLADA",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "403407",
                "nomeOrgaoJustica": "SECAO JUDICIARIA DE PE EM PALMARES",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "4.500,00",
                "valorTotalInscritoIndex": "4.228,92",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "5.576,67",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "4.500,00",
                "valorRemanescenteIndex": "4.228,92",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901400088"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "18208075029201579",
        "res": [
            {
                "inscricao": "40 7 19 004430-90",
                "processoAdministrativo": "18208 075029/2015-79",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "0810",
                "nomeReceita": "DIV.ATIVA-PIS",
                "codigoSerie": "7",
                "nomeSerie": "PROG INT SOCIAL/PROG FORM PATR SERV PUBL",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "52.299,95",
                "valorTotalInscritoIndex": "49.149,43",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "84.987,60",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "52.299,95",
                "valorRemanescenteIndex": "49.149,43",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4071900443090"
            },
            {
                "inscricao": "40 6 19 014002-40",
                "processoAdministrativo": "18208 075029/2015-79",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "1804",
                "nomeReceita": "DIV.ATIVA-CONTRIBUICAO SOCIAL",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "58.801,72",
                "valorTotalInscritoIndex": "55.259,56",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "96.027,84",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "58.801,72",
                "valorRemanescenteIndex": "55.259,56",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901400240"
            },
            {
                "inscricao": "40 4 19 018401-72",
                "processoAdministrativo": "18208 075029/2015-79",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3202",
                "nomeReceita": "DIV.ATIVA-CONTR. PREV. RECEITA",
                "codigoSerie": "4",
                "nomeSerie": "TRIBUTOS DIVERSOS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "7.185,38",
                "valorTotalInscritoIndex": "6.752,54",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "11.588,45",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "7.185,38",
                "valorRemanescenteIndex": "6.752,54",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4041901840172"
            },
            {
                "inscricao": "40 2 19 006853-30",
                "processoAdministrativo": "18208 075029/2015-79",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3551",
                "nomeReceita": "DIV.ATIVA-IRPJ",
                "codigoSerie": "2",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA JURIDICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "73.745,76",
                "valorTotalInscritoIndex": "69.303,40",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "120.367,72",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "73.745,76",
                "valorRemanescenteIndex": "69.303,40",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4021900685330"
            },
            {
                "inscricao": "40 6 19 014003-20",
                "processoAdministrativo": "18208 075029/2015-79",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "26/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "4493",
                "nomeReceita": "DIV.ATIVA-COFINS",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "241.384,41",
                "valorTotalInscritoIndex": "226.843,70",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "392.250,61",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "241.384,41",
                "valorRemanescenteIndex": "226.843,70",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4061901400320"
            }
        ],
        "total": 5
    },
    {
        "ok": true,
        "processo": "19647007929200939",
        "res": [
            {
                "inscricao": "40 1 19 001776-05",
                "processoAdministrativo": "19647 007929/2009-39",
                "situacao": "ATIVA A SER COBRADA",
                "dataInscricao": "12/07/2019",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "46.187,77",
                "valorTotalInscritoIndex": "43.405,46",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "107.009,46",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "46.187,77",
                "valorRemanescenteIndex": "43.405,46",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "01",
                "descricaoTipoSituacao": "EM COBRANCA",
                "tipoRegularidade": "IRREGULAR",
                "dataPostagem": "",
                "numeroCNO": "000000000000",
                "insc": "4011900177605"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "19647013453200461",
        "res": [
            {
                "inscricao": "40 1 05 000232-97",
                "processoAdministrativo": "19647 013453/2004-61",
                "situacao": "EXTINTA POR ANULACAO COM AJUIZAMENTO A SER CANCELADO",
                "dataInscricao": "30/05/2005",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "200583000142473",
                "numeroProcessoJudicialNovo": "200583000142473",
                "orgaoOrigem": "SECRET DA RECEITA FEDERAL DO BRASIL-RFB",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "402362",
                "descricaoJuizo": "22ª Vara Federal",
                "dataProtocoloJudExecucao": "29/09/2005",
                "dataDistribuicaoJudicial": "04/10/2005",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "227.963,22",
                "valorTotalInscritoIndex": "214.231,00",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "0,00",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "227.963,22",
                "valorRemanescenteIndex": "214.231,00",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "04/09/2008",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "FACE DESP. CH. SECAT/DRF/RCE/PE EM 22/08/2008 E AUT. PROCURADOR CHEFE DA PFN/PE EM 27/08/08 FLS. 235 DO PA 19647.013453/2004-61.",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "400005904013",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "06",
                "descricaoTipoSituacao": "EXTINTA",
                "tipoRegularidade": "REGULAR",
                "dataPostagem": "12/06/2005",
                "numeroCNO": "000000000000",
                "insc": "4010500023297"
            }
        ],
        "total": 1
    },
    {
        "ok": false,
        "processo": "19647017451200874",
        "res": null
    }
]`);
