
export default process.env.NODE_ENV === 'development' ?
JSON.parse(`[
    {
        "ok": false,
        "processo": "10480727321201203",
        "res": null
    },
    {
        "ok": false,
        "processo": "10480727314201201",
        "res": null
    },
    {
        "ok": false,
        "processo": "10480726814201137",
        "res": null
    },
    {
        "ok": false,
        "processo": "10480727315201248",
        "res": null
    },
    {
        "ok": false,
        "processo": "10480723580201923",
        "res": null
    },
    {
        "ok": false,
        "processo": "10480725318201832",
        "res": null
    },
    {
        "ok": false,
        "processo": "10421720054201825",
        "res": null
    },
    {
        "ok": true,
        "processo": "104800051429910",
        "res": [
            {
                "inscricao": "40 7 18 000696-00",
                "processoAdministrativo": "10480 005142/99-10",
                "situacao": "EXTINTA POR DECISAO ADMINISTRATIVA ORGAO DE ORIGEM DEV OU ARQ",
                "dataInscricao": "01/06/2018",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "0810",
                "nomeReceita": "DIV.ATIVA-PIS",
                "codigoSerie": "7",
                "nomeSerie": "PROG INT SOCIAL/PROG FORM PATR SERV PUBL",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "18.715,46",
                "valorTotalInscritoIndex": "17.896,29",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "0,00",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "18.715,46",
                "valorRemanescenteIndex": "17.896,29",
                "dataDevolucaoProcesso": "12/11/2018",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "03/10/2018",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "PROCESSO 10480.005142/99-10",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "06",
                "descricaoTipoSituacao": "EXTINTA",
                "tipoRegularidade": "REGULAR",
                "dataPostagem": "09/06/2018",
                "numeroCNO": "000000000000",
                "insc": "4071800069600"
            },
            {
                "inscricao": "40 6 18 012038-17",
                "processoAdministrativo": "10480 005142/99-10",
                "situacao": "EXTINTA POR DECISAO ADMINISTRATIVA ORGAO DE ORIGEM DEV OU ARQ",
                "dataInscricao": "01/06/2018",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "4493",
                "nomeReceita": "DIV.ATIVA-COFINS",
                "codigoSerie": "6",
                "nomeSerie": "DIVERSAS ORIGENS",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "000000",
                "descricaoJuizo": "Vara Desconhecida",
                "dataProtocoloJudExecucao": "",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "86.373,56",
                "valorTotalInscritoIndex": "82.592,94",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "0,00",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "86.373,56",
                "valorRemanescenteIndex": "82.592,94",
                "dataDevolucaoProcesso": "12/11/2018",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "03/10/2018",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "PROCESSO 10480.005142/99-10",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "06",
                "descricaoTipoSituacao": "EXTINTA",
                "tipoRegularidade": "REGULAR",
                "dataPostagem": "09/06/2018",
                "numeroCNO": "000000000000",
                "insc": "4061801203817"
            }
        ],
        "total": 2
    },
    {
        "ok": false,
        "processo": "10480726818201891",
        "res": null
    },
    {
        "ok": true,
        "processo": "19647013453200461",
        "res": [
            {
                "inscricao": "40 1 05 000232-97",
                "processoAdministrativo": "19647 013453/2004-61",
                "situacao": "EXTINTA POR ANULACAO COM AJUIZAMENTO A SER CANCELADO",
                "dataInscricao": "30/05/2005",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "200583000142473",
                "numeroProcessoJudicialNovo": "200583000142473",
                "orgaoOrigem": "SECRET DA RECEITA FEDERAL DO BRASIL-RFB",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "402362",
                "descricaoJuizo": "22ª Vara Federal",
                "dataProtocoloJudExecucao": "29/09/2005",
                "dataDistribuicaoJudicial": "04/10/2005",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "227.963,22",
                "valorTotalInscritoIndex": "214.231,00",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "0,00",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "227.963,22",
                "valorRemanescenteIndex": "214.231,00",
                "dataDevolucaoProcesso": "",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "04/09/2008",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "FACE DESP. CH. SECAT/DRF/RCE/PE EM 22/08/2008 E AUT. PROCURADOR CHEFE DA PFN/PE EM 27/08/08 FLS. 235 DO PA 19647.013453/2004-61.",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "400005904013",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "06",
                "descricaoTipoSituacao": "EXTINTA",
                "tipoRegularidade": "REGULAR",
                "dataPostagem": "12/06/2005",
                "numeroCNO": "000000000000",
                "insc": "4010500023297"
            }
        ],
        "total": 1
    },
    {
        "ok": true,
        "processo": "10480404183201521",
        "res": [
            {
                "inscricao": "40 1 16 000707-40",
                "processoAdministrativo": "10480 404183/2015-21",
                "situacao": "EXTINTA POR DECISAO JUDICIAL DEVOLVIDA OU ARQUIVADA",
                "dataInscricao": "20/05/2016",
                "numeroPFNResponsavel": "4000",
                "nomePFNResponsavel": "QUINTA REGIAO",
                "numeroPFNInscricao": "4000",
                "nomePFNInscricao": "QUINTA REGIAO",
                "numeroProcessoJudicial": "",
                "numeroProcessoJudicialNovo": "141776020164058300",
                "orgaoOrigem": "RFB-RECEITA FEDERAL DO BRASIL",
                "codigoNaturezaReceita": "0001",
                "nomeNaturezaReceita": "TRIBUTARIA",
                "codigoReceitaPrincipal": "3543",
                "nomeReceita": "DIV.ATIVA-IRPF",
                "codigoSerie": "1",
                "nomeSerie": "IMPOSTO DE RENDA PESSOA FISICA",
                "codigoOrgaoJustica": "400696",
                "nomeOrgaoJustica": "SECAO JUDICIARIA - RECIFE",
                "numeroJuizo": "402362",
                "descricaoJuizo": "22ª Vara Federal",
                "dataProtocoloJudExecucao": "06/10/2016",
                "dataDistribuicaoJudicial": "",
                "indicadorMoedaTotalInscrito": "R$",
                "valorTotalInscritoMoeda": "26.088,48",
                "valorTotalInscritoIndex": "24.516,93",
                "indicadorMoedaTotalConsolidado": "R$",
                "valorTotalConsolidadoMoeda": "0,00",
                "indicadorMoedaTotalRemanescente": "R$",
                "valorRemanescenteMoeda": "26.088,48",
                "valorRemanescenteIndex": "24.516,93",
                "dataDevolucaoProcesso": "12/06/2017",
                "numeroAutoInfracao": "",
                "dataDecretacaoFalencia": "30/07/2014",
                "dataFimProcurador": "",
                "numeroImovelITR": "",
                "dataExtincaoInscricao": "26/05/2017",
                "motivoSuspensaoExigibilidade": "",
                "numeroRipSpu": "",
                "indicadorAnaliseOrgaoOrigem": "NAO",
                "motivoExtincaoInscricao": "(NR.DECISAO JUDICIAL:00141776020164058300) 10080.003821/0417-17, FLS 2-3",
                "codigoSituacaoProtesto": "000",
                "nomeSituacaoProtesto": "SEM PROTESTO",
                "indicadorProtImpedAjuiz": "",
                "numeroAgrupamento": "400016905552",
                "numeroInscricaoOriginal": "00 0 00 000000-00",
                "numeroInscricaoDerivada1": "00 0 00 000000-00",
                "numeroInscricaoDerivada2": "00 0 00 000000-00",
                "numeroInscricaoDerivada3": "00 0 00 000000-00",
                "numeroInscricaoDerivada4": "00 0 00 000000-00",
                "numeroInscricaoDerivada5": "00 0 00 000000-00",
                "numeroInscricaoDerivada6": "00 0 00 000000-00",
                "numeroInscricaoDerivada7": "00 0 00 000000-00",
                "dcomp": "",
                "descricaoNaoCalculado": "",
                "codigoMunicipioSPU": 0,
                "codigoSistemaOrigem": "E",
                "descricaoSistemaOrigem": "ELETRONICO",
                "indicadorParcelamento": "",
                "codigoTipoSituacao": "06",
                "descricaoTipoSituacao": "EXTINTA",
                "tipoRegularidade": "REGULAR",
                "dataPostagem": "09/06/2016",
                "numeroCNO": "000000000000",
                "insc": "4011600070740"
            }
        ],
        "total": 1
    },
    {
        "ok": false,
        "processo": "19647017451200874",
        "res": null
    }
]`) : [];
